[tool.ruff]
line-length = 100
target-version = "py312"

# On ne lint pas les notebooks (sinon bruit inutile)
exclude = [
  "venv",
  ".venv",
  "__pycache__",
  ".pytest_cache",
  "notebooks",
]

# Sélection des règles
select = ["E", "F", "I", "B", "UP"]
ignore = ["E501"]

# Faux positif FastAPI sur File(...)
per-file-ignores = { "routers_layer/*.py" = ["B008"] }

[tool.ruff.isort]
known-first-party = ["data_layer", "logic_layer", "routers_layer", "schemas", "scripts", "tests"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-q"
